import glob
import os
import re

# Input_FILE = str(input("파일 이름:")) + ".txt"
# Output_FILE = "C" + Input_FILE +".txt"
import pandas as pd

import limit as limit

clean_list = ['중인', '만큼', '마찬가지', '꼬집었', "연합뉴스", "데일리", "동아일보", "중앙일보", "조선일보", "기자", "아", "휴", "아이구", "아이쿠", "아이고",
              "어", "나", "우리", "저희", "따라", "의해", "을", "를", "에", "의", "가", "머니투데이","연합뉴스", ]


def clean_text(text):
    cleaned_text = re.sub('([a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+☞)', ' ', text)
    cleaned_text = re.sub('(http|ftp|https)://(?:[-\w.]|(?:%[\da-fA-F]{2}))+【】', ' ', cleaned_text)
    cleaned_text = re.sub('([ㄱ-ㅎㅏ-ㅣ]+)', ' ', cleaned_text)
    cleaned_text = re.sub('<[^>]*>', ' ', cleaned_text)
    cleaned_text = re.sub(r'\([^)]*\)', ' ', cleaned_text)
    cleaned_text = re.sub('[^\w\s]', ' ', cleaned_text)
    cleaned_text = re.sub('[▼]', ' ', cleaned_text)
    cleaned_text = text.strip()
    cleaned_text = " ".join(text.split())


    cleaned_text = cleaned_text.replace("네이버에서 매일신문 구독하기", "")
    cleaned_text = cleaned_text.replace("매일신문 네이버 바로가기", "")
    cleaned_text = cleaned_text.replace("매일신문  바로가기", "")
    cleaned_text = cleaned_text.replace("ⓒ매일신문", "")
    cleaned_text = cleaned_text.replace("네이버에서 한겨레 구독하기", "")
    cleaned_text = cleaned_text.replace("신문 보는 당신은 핵인싸 조금 삐딱한 뉴스 딱", "")
    cleaned_text = cleaned_text.replace("신문 구독신청 삐딱한 뉴스 딱", "")
    cleaned_text = cleaned_text.replace("ⓒ한겨레신문", "")
    cleaned_text = cleaned_text.replace("장도리  그림마당 보기", "")
    cleaned_text = cleaned_text.replace("경향신문 바로가기  경향신문 구독신청하기 경향신문", "")
    cleaned_text = cleaned_text.replace("경향신문 최신기사  기사 제보하기 경향신문", "")
    cleaned_text = cleaned_text.replace(" 네이버 모바일에서 전자신문 채널 구독하기", "")
    cleaned_text = cleaned_text.replace(" 네이버 홈에서 전자신문 구독하기  ", "")
    cleaned_text = cleaned_text.replace(" 전자신문 바로가기   ", "")
    cleaned_text = cleaned_text.replace("ⓒ 전자신문  전자신문인터넷,", "")
    cleaned_text = cleaned_text.replace("장정욱양산시민신문 저작권자 오마이뉴스시민기자,  덧붙이는 글   이 기사는 양산시민신문 장정욱에도 실렸습니다.", "")
    cleaned_text = cleaned_text.replace(" 네이버에서 한국경제 뉴스를 받아보세요", "")
    cleaned_text = cleaned_text.replace("모바일한경 구독신청", "")
    cleaned_text = cleaned_text.replace("한경닷컴 바로가기", "")
    cleaned_text = cleaned_text.replace("ⓒ 한국경제", "")
    cleaned_text = cleaned_text.replace("구미뉴시스 박홍식 기자", "")
    cleaned_text = cleaned_text.replace("공감언론 뉴시스", "")
    cleaned_text = cleaned_text.replace("6431", "")
    cleaned_text = cleaned_text.replace("9900", "")
    cleaned_text = cleaned_text.replace("모바일 오픈 미술작품 가격을 공개합니다", "")
    cleaned_text = cleaned_text.replace("뉴시스 채널 구독하고 에어팟 프로 받아가세요", "")
    cleaned_text = cleaned_text.replace("오픈 미술작품 가격을 공개합니다", "")
    cleaned_text = cleaned_text.replace("뉴시스 빅데이터  주가시세표 바로가기", "")
    cleaned_text = cleaned_text.replace("선택 2020, 제21대 총선의 모든 것", "")
    cleaned_text = cleaned_text.replace("유명 미술작품 가격 공개", "")
    cleaned_text = cleaned_text.replace("네이버에서 뉴시스 구독하기", "")
    cleaned_text = cleaned_text.replace("ⓒ 공감언론 뉴시스통신사. 무단전재재배포 금지", "")
    cleaned_text = cleaned_text.replace("사진뉴시스", "")
    cleaned_text = cleaned_text.replace("뉴시스 제공", "")
    cleaned_text = cleaned_text.replace("부의 운명 바꾸고 싶다면 7가지 바꿔라", "")
    cleaned_text = cleaned_text.replace("세계 1,2위 부자는 잠을 얼마나 잘까 ", "")
    cleaned_text = cleaned_text.replace("장모 명의로 바뀐 집,", "")
    cleaned_text = cleaned_text.replace("이혼하면…", "")
    cleaned_text = cleaned_text.replace("줄리아 투자노트 ", "")
    cleaned_text = cleaned_text.replace("조 변호사의 가정상담소", "")
    cleaned_text = cleaned_text.replace("부동산 투자는 부릿지", "")
    cleaned_text = cleaned_text.replace("머니투데이 구독하기", "")
    cleaned_text = cleaned_text.replace("저작권자 ⓒ 돈이 보이는 리얼타임 뉴스 머니투데이,", "")
    cleaned_text = cleaned_text.replace("네이버 구독하기", "")

    cleaned_text = cleaned_text.replace("     지디넷코리아 홈페이지    네이버 채널 구독하기   ⓒ메가뉴스       .", "")

    cleaned_text = cleaned_text.replace("\t", "")
    cleaned_text = cleaned_text.replace("네이버 메인에서 조선일보 받아보기   조선닷컴 바로가기   조선일보 구독신청하기", "")
    cleaned_text = cleaned_text.replace(" ⓒ 조선일보", "")

    cleaned_text = cleaned_text.replace("디지털타임스  채널 구독    뉴스스탠드 구독 디지털타임스 홈페이지 바로가기", "")
    cleaned_text = cleaned_text.replace("네이버 뉴스스탠드에서 디지털타임스 구독 하세요", "")
    cleaned_text = cleaned_text.replace("스포츠서울 네이버 뉴스스탠드 오픈  기사제보", "")
    cleaned_text = cleaned_text.replace("ⓒ 스포츠서울", "")
    cleaned_text = cleaned_text.replace("네이버 뉴스스탠드에서 전자신문 뉴스를  대한민국 최강 전문 뉴스 콘텐츠 포털 전자신문 생생한 현장의 소식 밸리 , 스타일이 살아있는 자동차매거진 9 , 디지털세대의 쇼핑채널 이버즈 , 미리 보는 환경에너지의 미래 그린 , 비지니스의 코어 정보기술 전자신문 앱 다운받기 전자신문  광고문의 ⓒ 전자신문 전자신문인터넷,", "")

    cleaned_text = cleaned_text.replace("네이버 연합뉴스 채널 구독", "")
    cleaned_text = cleaned_text.replace("뭐 하고 놀까 흥", "")
    cleaned_text = cleaned_text.replace("확 달라진 연합뉴스 웹을 만나보세요", "")
    cleaned_text = cleaned_text.replace("확 달라진 연합뉴스를 만나보세요", "")
    cleaned_text = cleaned_text.replace("네이버에서 연합뉴스 구독하세요", "")
    cleaned_text = cleaned_text.replace("코로나19 속보는", "")
    cleaned_text = cleaned_text.replace("집중호우 속보는", "")
    cleaned_text = cleaned_text.replace("네이버 연합뉴스에서", "")
    cleaned_text = cleaned_text.replace("네이버 연합뉴스", "")
    cleaned_text = cleaned_text.replace("구독 클릭", "")
    cleaned_text = cleaned_text.replace("팩트체크", "")
    cleaned_text = cleaned_text.replace("구독클릭", "")
    cleaned_text = cleaned_text.replace("제보하기", "")
    cleaned_text = cleaned_text.replace("사진 제공  연합뉴스", "")
    cleaned_text = cleaned_text.replace("사진연합뉴스", "")
    cleaned_text = cleaned_text.replace("연합뉴스 자료사진", "")
    cleaned_text = cleaned_text.replace("구미연합뉴스", "")
    cleaned_text = cleaned_text.replace("대구연합뉴스", "")
    cleaned_text = cleaned_text.replace("세종연합뉴스", "")
    cleaned_text = cleaned_text.replace("서울연합뉴스", "")
    cleaned_text = cleaned_text.replace("안동연합뉴스", "")
    cleaned_text = cleaned_text.replace("부산연합뉴스", "")
    cleaned_text = cleaned_text.replace("포항연합뉴스", "")
    cleaned_text = cleaned_text.replace("연합뉴스", "")

    cleaned_text = cleaned_text.replace("온라인 중앙일보", "")
    cleaned_text = cleaned_text.replace("내 돈 관리는 그게머니", "")
    cleaned_text = cleaned_text.replace("중앙일보 홈페이지", "")
    cleaned_text = cleaned_text.replace("중앙일보 가기", "")
    cleaned_text = cleaned_text.replace("페이스북 친구추가", "")
    cleaned_text = cleaned_text.replace("ⓒ중앙일보", "")

    cleaned_text = cleaned_text.replace("동아일보 단독 뉴스", "")
    cleaned_text = cleaned_text.replace("트렌드 뉴스", "")
    cleaned_text = cleaned_text.replace("네이버 홈에서 동아일보 채널 구독하기", "")
    cleaned_text = cleaned_text.replace("네이버에서 동아일보 채널 구독하기", "")
    cleaned_text = cleaned_text.replace("집 볼 때 쓰는 메모장 집보장", "")
    cleaned_text = cleaned_text.replace("트롯가수 응원은 트롯픽에서", "")
    cleaned_text = cleaned_text.replace("ⓒ 동아일보", "")
    cleaned_text = cleaned_text.replace("ⓒ 조세일보", "")

    cleaned_text = cleaned_text.replace("24시간 빠른 미리보는 뉴스", "")
    cleaned_text = cleaned_text.replace("네이버에서 ‘이데일리’ 구독하기", "")
    cleaned_text = cleaned_text.replace("네이버 홈에서 ‘이데일리’ 뉴스  구독하기", "")
    cleaned_text = cleaned_text.replace("24시간 전 미리보는 뉴스", "")
    cleaned_text = cleaned_text.replace("네이버에서 이데일리 뉴스를 만나보세요", "")
    cleaned_text = cleaned_text.replace("청춘뉘우스", "")
    cleaned_text = cleaned_text.replace("스냅타임", "")
    cleaned_text = cleaned_text.replace("빡침해소,", "")
    cleaned_text = cleaned_text.replace("꿀잼가득  영상보기", "")
    cleaned_text = cleaned_text.replace("＜ⓒ종합 경제정보 미디어 이데일리  무단전재  재배포 금지＞", "")
    cleaned_text = cleaned_text.replace("ⓒ 강원일보", "")
    cleaned_text = cleaned_text.replace("네이버 채널에서 아이뉴스24를 구독해주세요.", "")
    cleaned_text = cleaned_text.replace("재밌는 아이뉴스 영상보기", "")
    cleaned_text = cleaned_text.replace("아이뉴스24 바로가기", "")
    cleaned_text = cleaned_text.replace("아이뉴스24", "")

    cleaned_text = cleaned_text.replace("본 기사는 헤럴드경제로부터 제공받은 기사입니다", "")
    cleaned_text = cleaned_text.replace("네이버에서 헤럴드경제 채널 구독하기", "")
    cleaned_text = cleaned_text.replace("제49회 헤럴드 전국 영어 말하기대회", "")
    cleaned_text = cleaned_text.replace("헤럴드경제 사이트 바로가기", "")
    cleaned_text = cleaned_text.replace("헤럴드경제 네이버 채널 구독", "")
    cleaned_text = cleaned_text.replace("코로나19 현황보기", "")
    cleaned_text = cleaned_text.replace("디콘 여론조사를 조사하다", "")
    cleaned_text = cleaned_text.replace("헤럴드 ‘팩트체커’ 진실은 바로 이것", "")
    cleaned_text = cleaned_text.replace("코리아헤럴드 플립화상영어 무료체험", "")
    cleaned_text = cleaned_text.replace("ⓒ 헤럴드경제", "")
    cleaned_text = cleaned_text.replace("헤럴드경제 모바일 웹", "")
    cleaned_text = cleaned_text.replace("헤럴드경제 모바일앱", "")
    cleaned_text = cleaned_text.replace("헤럴드경제", "")
    cleaned_text = cleaned_text.replace("뉴스스탠드 헤럴드", "")
    cleaned_text = cleaned_text.replace("코리아헤럴드", "")
    cleaned_text = cleaned_text.replace("헤럴드시티", "")
    cleaned_text = cleaned_text.replace("헤럴드증권방송", "")
    cleaned_text = cleaned_text.replace("주니어 헤럴드", "")
    cleaned_text = cleaned_text.replace("주니어헤럴드", "")

    cleaned_text = cleaned_text.replace("네이버 메인에서 조선비즈 받아보기", "")
    cleaned_text = cleaned_text.replace("네이버에서 조선비즈를 구독 하세요", "")
    cleaned_text = cleaned_text.replace("조선비즈 창간 10주년 기획 다시쓰다 도시3.0 기사 보러가기", "")
    cleaned_text = cleaned_text.replace("조선비즈 바로가기", "")
    cleaned_text = cleaned_text.replace("조선비즈 바로 가기", "")
    cleaned_text = cleaned_text.replace("명품 경제뉴스", "")
    cleaned_text = cleaned_text.replace("ⓒ 조선비즈", "")


    cleaned_text = cleaned_text.replace("무단전재 및 재배포금지", "")

    cleaned_text = cleaned_text.replace("데일리", "")
    cleaned_text = cleaned_text.replace("머니투데이", "")

    cleaned_text = cleaned_text.replace("춘천뉴시스", "")
    cleaned_text = cleaned_text.replace("김천뉴시스", "")
    cleaned_text = cleaned_text.replace("경주뉴시스", "")
    cleaned_text = cleaned_text.replace("대전뉴시스", "")
    cleaned_text = cleaned_text.replace("구미뉴시스", "")
    cleaned_text = cleaned_text.replace("서울뉴시스", "")
    cleaned_text = cleaned_text.replace("대구뉴시스", "")
    cleaned_text = cleaned_text.replace("전주뉴시스", "")
    cleaned_text = cleaned_text.replace("경북뉴시스", "")
    cleaned_text = cleaned_text.replace("군위뉴시스", "")
    cleaned_text = cleaned_text.replace("고령뉴시스", "")
    cleaned_text = cleaned_text.replace("진주뉴시스", "")
    cleaned_text = cleaned_text.replace("뉴시스 뉴스", "")
    cleaned_text = cleaned_text.replace("모바일 뉴시스", "")
    cleaned_text = cleaned_text.replace("괴산뉴시스", "")
    cleaned_text = cleaned_text.replace("거제뉴시스", "")
    cleaned_text = cleaned_text.replace("홍성·예산뉴시스", "")
    cleaned_text = cleaned_text.replace("영동뉴시스", "")
    cleaned_text = cleaned_text.replace("세종뉴시스", "")
    cleaned_text = cleaned_text.replace("괴산·증평", "")
    cleaned_text = cleaned_text.replace("거창뉴시스", "")
    cleaned_text = cleaned_text.replace("안동뉴시스", "")
    cleaned_text = cleaned_text.replace("인천공항뉴시스", "")
    cleaned_text = cleaned_text.replace("성남뉴시스", "")
    cleaned_text = cleaned_text.replace("칠곡뉴시스", "")
    cleaned_text = cleaned_text.replace("인천뉴시스", "")
    cleaned_text = cleaned_text.replace("부산뉴시스", "")
    cleaned_text = cleaned_text.replace("순천뉴시스", "")
    cleaned_text = cleaned_text.replace("창원뉴시스", "")
    cleaned_text = cleaned_text.replace("포항뉴시스", "")
    cleaned_text = cleaned_text.replace("충주뉴시스", "")
    cleaned_text = cleaned_text.replace("익산뉴시스", "")
    cleaned_text = cleaned_text.replace("포항뉴시스", "")
    cleaned_text = cleaned_text.replace("포항뉴시스", "")
    cleaned_text = cleaned_text.replace("포항뉴시스", "")

    cleaned_text = cleaned_text.replace("☞", "")
    cleaned_text = cleaned_text.replace("오늘의 동아일보", "")
    cleaned_text = cleaned_text.replace("동아 기사", "")
    cleaned_text = cleaned_text.replace("채널 종합뉴스", "")

    cleaned_text = cleaned_text.replace("주요 이슈의 재구성, 촌철살인 이미지 파일 카드뉴스 재미있는 동영상이 모두 모였다 펀캐스트", "")
    cleaned_text = cleaned_text.replace("ⓒ세계를 보는 창 경제를 보는 눈, 아시아경제 무단전재 배포금지", "")
    cleaned_text = cleaned_text.replace("정치뉴스의 모든 것 레이더  기사의 저작권은 레이더 에 있습니다. 지면 혹은 방송을 통한 인용 보도시 출처를 밝혀주시기 바랍니다.", "")




    cleaned_text = cleaned_text.replace("뉴스 가치나 화제성이 있다고 판단되는 사진 또는 영상을 뉴시스 사진영상부", "")
    cleaned_text = cleaned_text.replace("027217470로 보내주시면 적극 반영하겠습니다.", "")

    cleaned_text = cleaned_text.replace("【 대구김장욱 기자】", "")

    cleaned_text = cleaned_text.replace("네이버 구독하기", "")
    cleaned_text = cleaned_text.replace("네이버에서 구독하기", "")
    cleaned_text = cleaned_text.replace("네이버 바로가기", "")

    cleaned_text = cleaned_text.replace("채널 구독", "")

    cleaned_text = cleaned_text.replace("＜종합 경제정보 미디어 이  무단전재  재배포 금지＞", "")
    cleaned_text = cleaned_text.replace("받아보기", "")
    cleaned_text = cleaned_text.replace("네이버에서 조선비즈를 구독 하세요", "")
    cleaned_text = cleaned_text.replace("조선닷컴", "")

    cleaned_text = cleaned_text.replace("오마이뉴스", "")
    cleaned_text = cleaned_text.replace("국민일보", "")
    cleaned_text = cleaned_text.replace("구독하세요", "")
    cleaned_text = cleaned_text.replace("바로가기", "")
    cleaned_text = cleaned_text.replace("무단전재 및 재배포금지", "")
    cleaned_text = cleaned_text.replace("한국일보닷컴 바로가기", "")
    cleaned_text = cleaned_text.replace("네이버에서 한국일보 뉴스를 받아보세요", "")
    cleaned_text = cleaned_text.replace("한국일보", "")
    cleaned_text = cleaned_text.replace("뉴잼을 보면 뉴스가 재밌다 뉴스레터 구독하기", "")
    cleaned_text = cleaned_text.replace("대한민국 오후를 여는 유일석간 문화일보", "")
    cleaned_text = cleaned_text.replace("문화일보", "")
    cleaned_text = cleaned_text.replace("구독신청:0237015555", "")
    cleaned_text = cleaned_text.replace("무단전재재배포 금지", "")
    cleaned_text = cleaned_text.replace("강원일보", "")
    cleaned_text = cleaned_text.replace("세상을 보는 눈,  세계일보", "")
    cleaned_text = cleaned_text.replace("세계일보", "")

    cleaned_text = cleaned_text.replace("네이버 메인에서", "")
    cleaned_text = cleaned_text.replace("뉴스1 구독하기", "")
    cleaned_text = cleaned_text.replace("코로나19 뉴스", "")
    cleaned_text = cleaned_text.replace("뉴스1코리아 1.", "")
    cleaned_text = cleaned_text.replace("네이버 채널에서 서울경제 구독해주세요", "")
    cleaned_text = cleaned_text.replace("세상 모든 것에 대해 던지는 질문, 왜 저작권자  서울경제", "")
    cleaned_text = cleaned_text.replace("서울경제", "")
    cleaned_text = cleaned_text.replace("공감언론", "")
    cleaned_text = cleaned_text.replace("뉴스1 구독하기", "")
    cleaned_text = cleaned_text.replace("구독하기", "")
    cleaned_text = cleaned_text.replace("저작권자 시민기자", "")

    cleaned_text = cleaned_text.replace("구독신청하기", "")
    cleaned_text = cleaned_text.replace("확 달라진 노컷뉴스  클릭 한 번이면 노컷뉴스 구독  보다 나은 세상", "")
    cleaned_text = cleaned_text.replace("노컷브이와 함께", "")
    cleaned_text = cleaned_text.replace("노컷뉴스", "")
    cleaned_text = cleaned_text.replace("파이낸셜뉴스", "")
    cleaned_text = cleaned_text.replace("무단 전재재배포 금지", "")
    cleaned_text = cleaned_text.replace("명품 경제뉴스  바로 가기", "")
    cleaned_text = cleaned_text.replace("프리미엄 북한뉴스", "")
    cleaned_text = cleaned_text.replace("한반도 구독", "")
    cleaned_text = cleaned_text.replace("뭐 하고 놀까 흥", "")
    cleaned_text = cleaned_text.replace("클릭 제보하기", "")
    cleaned_text = cleaned_text.replace("구미뉴스1", "")
    cleaned_text = cleaned_text.replace("뉴스1", "")
    cleaned_text = cleaned_text.replace("단독 뉴스", "")
    cleaned_text = cleaned_text.replace("네이버 모바일에서  하기", "")
    cleaned_text = cleaned_text.replace("트렌드 뉴스  네이버 홈에서  하기", "")
    cleaned_text = cleaned_text.replace("취향저격 뉴스는 여기   의뢰하세요 취재대행소 왱", "")
    cleaned_text = cleaned_text.replace("네이버 홈에서 ‘이’ 뉴스   꿀잼가득  영상보기", "")
    cleaned_text = cleaned_text.replace("문화닷컴     가 직접 편집한 뉴스 채널    모바일 웹", "")
    cleaned_text = cleaned_text.replace("구독신청", "")
    cleaned_text = cleaned_text.replace("모바일한경", "")

    cleaned_text = cleaned_text.replace("돈이 보이는", "")
    cleaned_text = cleaned_text.replace("저작권자", "")
    cleaned_text = cleaned_text.replace("..", "")
    cleaned_text = cleaned_text.replace("888", "")
    cleaned_text = cleaned_text.replace("우리 동네 무슨 일이 지역뉴스 더 빠르고 정확한 소식을 원하시면 뉴스 구독", "")
    cleaned_text = cleaned_text.replace("아시아경제 뉴스를 받아보세요 요즘 트렌드 모아보고 싶을 땐 드링킷 경제를 보는 눈, 세계를 보는 창 아시아경제 무단전재 배포금지", "")
    cleaned_text = cleaned_text.replace("재물운·연애운·건강운 체크", "")

    cleaned_text = cleaned_text.replace("네이버 채널에서 를정치채널 뉴스보야쥬 넷따잡 뷰잉 영상보기  닷컴 ", "")
    cleaned_text = cleaned_text.replace("한경닷컴", "")
    cleaned_text = cleaned_text.replace("닷컴", "")
    cleaned_text = cleaned_text.replace("동영상 뉴스", "")
    cleaned_text = cleaned_text.replace("뉴스레터 매콤달콤 구독", "")
    cleaned_text = cleaned_text.replace("코인 지금 가입하면 5000코인 드려요 매일경제를 받아보세요", "")
    cleaned_text = cleaned_text.replace("매일경제", "")
    cleaned_text = cleaned_text.replace("사진 영상 제보받습니다 가 독자 여러분의 소중한 제보를 기다립니다. 뉴스 가치나 화제성이 있다고 판단되는 사진 또는 영상을 뉴시스 사진영상부., 027217470로 보내주시면 적극 반영하겠습니다. , 이젠 네이버 뉴스 스탠드에서도 만나세요 손 안에서 보는 세상,  ⓒ 통신사.","")
    cleaned_text = cleaned_text.replace("이젠 네이버 뉴스 스탠드에서도 만나세요 손 안에서 보는 세상,  ⓒ 통신사.", "")
    cleaned_text = cleaned_text.replace("ⓒ 통신사","")
    cleaned_text = cleaned_text.replace("네이버 뉴스스탠드에서 전자신문 뉴스를  대한민국 최강 전문 뉴스 콘텐츠 포털 전자신문 생생한 현장의 소식 밸리 , 스타일이 살아있는 자동차매거진 9 , 디지털세대의 쇼핑채널 이버즈 , 미리 보는 환경에너지의 미래 그린 , 비지니스의 코어 정보기술 전자신문 앱 다운받기 전자신문  광고문의 ⓒ 전자신문 전자신문인터넷,", "")
    cleaned_text = cleaned_text.replace("네이버 뉴스스탠드 , 페이스북 , 트위터 에서 한국경제 를 바로 만나보세요", "")
    cleaned_text = cleaned_text.replace("네이버 뉴스스탠드에서 를 뉴스로   모바일 서비스 페이스북  ", "")
    cleaned_text = cleaned_text.replace("사진방송화면 캡처 심심하면 들어와 인기 무료만화 스포츠서울 네이버 뉴스스탠드 오픈  기사제보 ", "")
    cleaned_text = cleaned_text.replace("미즈리포트 포토","")
    cleaned_text = cleaned_text.replace("대박 이벤트 무료 만화","")
    cleaned_text = cleaned_text.replace("무료 만화 오늘의 운세", "")
    cleaned_text = cleaned_text.replace("ⓒ 세상을 보는 눈", "")
    cleaned_text = cleaned_text.replace("공식 페이스북 트위터 인기화보 인기만화 핫이슈 ⓒ 한겨레신문사, 한겨레는 한국온라인신문협회 . 의 디지털뉴스이용규칙에 따른 저작권을 행사합니다.", "")
    cleaned_text = cleaned_text.replace("페이스북 신문에는 없는 뉴스 꿀잼 동영상 ⓒ", "")
    cleaned_text = cleaned_text.replace("부담없이 즐기는 서울신문 ‘최신만화’  ⓒ 서울신문사", "")
    cleaned_text = cleaned_text.replace("페이스북 좋아요 클릭클릭 썸 타는 특별한 뉴스 썸 페이스북", "")
    cleaned_text = cleaned_text.replace("화이트데이 인기 운세 50 할인 이벤트 서울신문  서울신문 페이스북 서울신문 전체보기 포토뉴스 서울 동영상뉴스 서울 놀라운 글로벌세상 나우뉴스 ⓒ서울신문사", "")
    cleaned_text = cleaned_text.replace("위클리비즈 페이스북 카카오스토리", "")
    cleaned_text = cleaned_text.replace("페이스북  프로야구 스카우팅리포트 앱다운로드 요지경세상 펀펀 ⓒ", "")

    cleaned_text = cleaned_text.replace("모바일 경향 경향 뉴스진 경향신문 앱 모바일웹 공식","")
    cleaned_text = cleaned_text.replace("계정 경향 트위터 페이스북","")
    cleaned_text = cleaned_text.replace("계정 트위터 페이스북", "")
    cleaned_text = cleaned_text.replace("〈경향신문은 한국온라인신문협회", "")
    cleaned_text = cleaned_text.replace("의 디지털뉴스이용규칙에 따른 저작권을 행사합니다.〉", "")
    cleaned_text = cleaned_text.replace("스포츠경향 뉴스를 네이버 뉴스 스탠드에서 만나 보세요.", "")
    cleaned_text = cleaned_text.replace("세상과 경향의 소통 커뮤니티 ⓒ 경향신문", "")
    cleaned_text = cleaned_text.replace("ⓒ 스포츠경향 경향", "")
    cleaned_text = cleaned_text.replace("경향은 한국온라인신문협회", "")
    cleaned_text = cleaned_text.replace("주간경향 공식 계정 페이스북 트위터 모바일 주간경향 모바일웹 경향 뉴스진", "")
    cleaned_text = cleaned_text.replace("ⓒ 주간경향", "")

    cleaned_text = cleaned_text.replace("무료 만화 서비스 오픈", "")

    cleaned_text = cleaned_text.replace("나우뉴스부  부담없이 즐기는 서울신문 ‘최신만화’ 나우뉴스 . 페이스북 군사·무기 별별남녀 기상천외 중국  ⓒ 서울신문사", "")
    cleaned_text = cleaned_text.replace("종합 경제 뉴스 이 모바일 웹 이 이 트래블러 마켓포인트 투자정보 앱 투자플러스 이 창업 ＜ⓒ종합 경제정보 미디어 이 무단전재 재배포 금지＞", "")
    cleaned_text = cleaned_text.replace("기자들의 생생한 취재현장 뒷이야기 취재파일", "")
    cleaned_text = cleaned_text.replace("자신있게 내놓은 자식들 스브스뉴스", "")
    cleaned_text = cleaned_text.replace("뉴스 공식 8 트위터 페이스북 카카오스토리  콘텐츠허브 무단복제재배포 금지", "")
    cleaned_text = cleaned_text.replace("취재후 방송에서 못한 현장 이야기 뉴스 트위터 페이스북 카카오 ⓒ 무단복제재배포 금지", "")
    cleaned_text = cleaned_text.replace("공식 페이스북 트위터", "")
    cleaned_text = cleaned_text.replace("【】", "")
    cleaned_text = cleaned_text.replace("화끈한 토픽·쏠쏠한 정보 조세일보 페이스북 초대합니다.", "")




    return str(cleaned_text)



